### ISSUE TITLE
Bug em tipo de erro

### ISSUE THREAD

**Issue by fakiot** [gabstv/correios#3]
Os tipos de erro ErrAreaPrazoDiferenciado e ErrAreaDeRiscoCEPs nas linhas https://github.com/gabstv/correios/blob/master/frete.go#L152 e
https://github.com/gabstv/correios/blob/master/frete.go#L153
estão com valores errados, pois deveriam ser 10 e 11 respectivamente, mas como iniciam com "0" o Go entende como octal, resultando em 8 e 9 respectivamente https://golang.org/ref/spec#octal_digits

**Comment by gabstv** [comment]
fixed @ b10a52c6452a394977e56004000f3447339cca8e
